Update to latest version of `regex` Python package
This is a dependency of the `black` Python code formatter used by this project. An incompatibility with the previously
used version of `regex` was introduced in black@21.11b0, which resulted an error when running it:

```
• Installing regex (2020.11.13)
[...]
task: [python:format] poetry run black .
Traceback (most recent call last):
  File "/home/runner/.cache/pypoetry/virtualenvs/arduino-lint-E2I5XaEt-py3.9/bin/black", line 5, in <module>
    from black import patched_main
  File "/home/runner/.cache/pypoetry/virtualenvs/arduino-lint-E2I5XaEt-py3.9/lib/python3.9/site-packages/black/__init__.py", line 39, in <module>
    from black.nodes import STARS, syms, is_simple_decorator_expression
  File "/home/runner/.cache/pypoetry/virtualenvs/arduino-lint-E2I5XaEt-py3.9/lib/python3.9/site-packages/black/nodes.py", line 31, in <module>
    from black.strings import has_triple_quotes
  File "/home/runner/.cache/pypoetry/virtualenvs/arduino-lint-E2I5XaEt-py3.9/lib/python3.9/site-packages/black/strings.py", line 159, in <module>
    def _cached_compile(pattern: str) -> re.Pattern:
AttributeError: module 'regex' has no attribute 'Pattern'
task: Failed to run task "python:format": exit status 1
```

but the black developers seem to have missed updating their version constraints accordingly so the dependency must be
updated manually:

https://github.com/psf/black/blob/21.11b0/Pipfile#L45