Bump github.com/ulikunitz/xz from 0.5.14 to 0.5.15
This is necessary to fix a regression introduced by 0.5.14, which caused builds for 32-bit hosts to fail:

```
/go/pkg/mod/github.com/ulikunitz/xz@v0.5.14/lzma/reader.go:33:15: cannot use 1 << 31 (untyped int constant 2147483648) as int value in assignment (overflows)
Error: failed building for linux/armv6: exit status 1
failed building for linux/armv6: exit status 1
task: Failed to run task "dist:Linux_ARMv6": exit status 1
```