Remove spurious blank lines from rule output
The `github.com/olekukonko/tablewriter` package used for formatting of the rule output does not correctly handle text
with explicit (as opposed by ones added during auto-wrapping) line breaks.

With reflow enabled, these explicit line breaks are removed and the line wrapped solely based on the column width, just
as it would be without the explicit line breaks. For example, given this rule message:

```
.exe file(s) found. Presence of these files blocks addition to the Library Manager index:
deleteme-testdata\bar.exe
deleteme-testdata\examples\baz.exe
deleteme-testdata\examples\qux\asdf.exe
(Rule LS007)
```

The output is:

```
ERROR: .exe file(s) found. Presence of these files blocks addition to the Library
       Manager index: deleteme-testdata/bar.exe deleteme-testdata/examples/baz.exe
       deleteme-testdata/examples/qux/asdf.exe (Rule LS007)
```

With reflow disabled, each explicit line break becomes a blank line:

```
ERROR: .exe file(s) found. Presence of these files blocks addition to the Library Manager index:

       deleteme-testdata/bar.exe

       deleteme-testdata/examples/baz.exe

       deleteme-testdata/examples/qux/asdf.exe

       (Rule LS007)
```

I could not find any way to coerce the package to produce the desired output:

```
ERROR: .exe file(s) found. Presence of these files blocks addition to the Library Manager index:
       deleteme-testdata/bar.exe
       deleteme-testdata/examples/baz.exe
       deleteme-testdata/examples/qux/asdf.exe
       (Rule LS007)
```

so I had to resort to post-processing of the non-reflowed output to remove the spurious blank lines.